language: php
sudo: false

env:
  - XDEBUG_MODE=coverage

php:
  - 7.3
  - 7.4
  - 8.0

before_install:
  - composer self-update

cache:
  directories:
    - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phing build

after_success:
  - travis_retry php vendor/bin/coveralls
